```{r}
rm(list = ls())
library(SummarizedExperiment)
library(readxl)
library(impute)
library(ggplot2)
library(ggforce)
library(vegan)
library(tidyr)
library(dplyr) 
library(tibble)
library(DESeq2)
library(pheatmap)
library(RColorBrewer)
library(ggrepel)
library(plotly)
library(writexl)
```


```{r}
orig <- read_excel("gene_expression.xlsx") %>% as.data.frame()
colData <- read_excel("datasheet.xlsx") %>% as.data.frame()
rownames(colData) <- colData$Sample
```
```{r}
sample_order <- c("AL1", "AL2", "AL3", "AL4", "AL5", "AL6", "Fast1","Fast2", "Fast3", "Fast4", "Fast5", "Fast6")
ordered_ids <- colData$ID[match(sample_order, colData$Sample)]
count_matrix <- orig %>% dplyr::select(gene = `Gene ID`, all_of(paste0(ordered_ids, ".count")))
colnames(count_matrix)[2:ncol(count_matrix)] <- sample_order
rownames(count_matrix) <- count_matrix$gene
count_matrix$gene <- NULL
count_matrix <- as.matrix(count_matrix)
```

```{r}
rowData <- orig %>%dplyr::select(`Gene ID`, `Gene Name`, `Gene Type`, Chromosome)

rowData <- rowData[match(rownames(count_matrix), rowData$`Gene ID`), ]

rownames(rowData) <- rowData$`Gene ID`
rowData$`Gene ID` <- NULL

print(head(rownames(count_matrix), 5))
print(head(rownames(rowData), 5))
print(head(rowData))
```

```{r}
count_matrix_round <- round(count_matrix)
gse <- SummarizedExperiment(
  assays = list(counts = count_matrix_round),
  rowData = rowData,
  colData = colData
)
print(gse)

```

### QC

```{r}
nrow(gse)
smallestGroupSize <- 6
minCount <- 5
keep <- rowSums(assay(gse) >= minCount) >= smallestGroupSize
gse <- gse[keep,]
nrow(gse)
```
```{r}
# saveRDS(gse, "BulkRNAgse.rds")
```

### Table S3. Bulk_RNAsq_DEGs.xlsx

```{r}
library(DESeq2)
dds <- DESeqDataSet(gse, design = ~ group)
dds <- DESeq(dds)

res <- results(dds, contrast = c("group", "Fast", "AL"))
res <- as.data.frame(res)
res$gene <- rowData(gse)$'Gene Name'

write_xlsx(res, path = "Table S3. Bulk_RNAsq_DEGs.xlsx")
```

### Table S4. Bulk_RNAsq_GSEA.xlsx

```{r}
library(clusterProfiler)
library(org.Mm.eg.db)
gene_data <- data.frame(
  SYMBOL = res$gene,
  stat = res$stat
)

gene_data <- gene_data[!is.na(gene_data$SYMBOL), ]


gene_data <- aggregate(stat ~ SYMBOL, data = gene_data, FUN = mean)


geneList <- gene_data$stat

names(geneList) <- gene_data$SYMBOL

geneList <- sort(geneList, decreasing = TRUE)

head(geneList)
```

```{r fig.height=12, fig.width=10}
gsea_go_results <- gseGO(
  geneList     = geneList,
  OrgDb        = org.Mm.eg.db,
  keyType      = "SYMBOL",
  ont          = "ALL",
  pvalueCutoff = 0.05,
  pAdjustMethod = "BH",
  verbose      = TRUE
)
cat("GSEA complete.\n")

temp <- as.data.frame(gsea_go_results@result)
write_xlsx(temp, "Table S4. Bulk_RNAsq_GSEA.xlsx")
```





