```{r message=FALSE}
rm(list = ls())
library(Seurat)
library(cowplot)
library(patchwork)
library(tidyverse)
library(SeuratWrappers)
library(ggplot2)
library(harmony)
library(SoupX)
library(Matrix)
library(DropletUtils)
library(scDblFinder)
set.seed(77)
```

```{r}
library(future)
options(future.globals.maxSize = 40 * 1024^3)

```

### Functions 

```{r}
## ---- QC ----
pp <- function(obj){
  obj[["percent.mt"]] <- PercentageFeatureSet(obj, pattern = "^mt-")
  bool_vector <-  (obj$percent.mt < 5) & (obj$nCount_RNA > 500) & (obj$nFeature_RNA > 400)
  obj <- subset(obj, cells = which(bool_vector))
  return(obj)
}
```

```{r}
Diet <- function(obj) {
  obj <- DietSeurat(obj, assays = "RNA", layers = "counts")
  return(obj)
}
```

```{r}
## ---- normalization ----
Norm <- function(obj, vars.to.regress =  "percent.mt") {
  obj <- NormalizeData(obj, normalization.method = "LogNormalize", scale.factor = 10000)
  obj <- FindVariableFeatures(obj, selection.method = "vst", nfeatures = 2000)
  obj <- ScaleData(obj, vars.to.regress = vars.to.regress)
  obj <- RunPCA(obj, assay = "RNA")
  return(obj)
}
```


```{r}
## ---- normalization (harmony)----
NormHarmony <- function(obj, vars.to.regress = "percent.mt") {
  obj <- NormalizeData(obj, normalization.method = "LogNormalize", scale.factor = 10000)
  obj <- FindVariableFeatures(obj, selection.method = "vst", nfeatures = 2000)
  obj <- ScaleData(obj, vars.to.regress = vars.to.regress)
  obj <- RunPCA(obj, assay = "RNA")
  obj <- RunHarmony(obj, group.by.vars = "group", reduction = "pca", assay.use = "RNA",reduction.save = "harmony")
  return(obj)
}
```

```{r}
PcaUmap <- function(obj, dims = 1:20, graph.name = NULL) {
  obj <- FindNeighbors(obj, reduction = "pca", dims = dims, )
  obj <- RunUMAP(obj, reduction = "pca", dims = dims)
  return(obj)
}
```

```{r}
PcaTsne <- function(obj, dims = 1:20, graph.name = NULL) {
  obj <- FindNeighbors(obj, reduction = "pca", dims = dims)
  obj <- RunTSNE(obj, reduction = "pca", dims = dims)
  return(obj)
}
```

```{r}
HarmonyUmap <- function(obj, dims = 1:20, graph.name = NULL) {
  obj <- FindNeighbors(obj, reduction = "harmony", dims = dims)
  obj <- RunUMAP(obj, reduction = "harmony", dims = dims)
  return(obj)
}
```

```{r}
HarmonyTsne <- function(obj, dims = 1:20, graph.name = NULL) {
  obj <- FindNeighbors(obj, reduction = "harmony", dims = dims)
  obj <- RunTSNE(obj, reduction = "harmony", dims = dims)
  return(obj)
}
```

```{r}
## ---- run emptyDrops ----
rmEmpty <- function(obj, filtered_obj = NULL) {
  set.seed(77)
  e.out <- emptyDrops(obj,retain = 12000,lower = 15, alpha = NULL)
  is.cell <- e.out$FDR <= 0.001
  cat("Identified", sum(is.cell, na.rm = TRUE), "cells.\n")
  obj <- obj[, which(is.cell)]
  obj <- obj[which(rownames(obj) %in% rownames(filtered_obj)),]
  obj <- CreateSeuratObject(obj)
  obj[["percent.mt"]] <- PercentageFeatureSet(obj, pattern = "^mt-")
  return(obj)
}
```


```{r}
## ---- SoupX ----
rmSoup <- function(obj, Raw_obj = NULL, group = NULL) {
  DefaultAssay(obj) <- "RNA"
  toc <- GetAssayData(obj, assay = "RNA", layer = "counts")
  tod <- Raw_obj
  tod <- tod[which(rownames(tod) %in% rownames(toc)),]
  sc <- SoupChannel(tod, toc, calcSoupProfile = T)
  sc <- setClusters(sc, setNames(obj$seurat_clusters, colnames(obj)))
  sc <- setContaminationFraction(sc, contFrac = 0.2)
  sc <- adjustCounts(sc, roundToInt = T)
  obj <- CreateSeuratObject(sc, project = group, min.cells = 20)
  obj$group <- obj$orig.ident
  obj[["percent.mt"]] <- PercentageFeatureSet(obj, pattern = "^mt-")
  return(obj)
}
```

```{r}
## ---- scDblFinder ----
FindDbl <- function(obj) {
  sce <- obj %>% Diet() %>% as.SingleCellExperiment()
  sce <- scDblFinder(sce, clusters = obj$seurat_clusters, dbr.sd = 1)
  obj$scDblFinder.class <- sce$scDblFinder.class
  return(obj)
}
```



```{r}
## ---- remove doublet and low-quality clusters ----
rmLowquality <- function(obj, LowQualityClusters = NULL, rmDoublets = TRUE) {
  obj <- pp(obj)
  Idents(obj) <- "seurat_clusters"
  obj <- subset(obj, idents = LowQualityClusters, invert = TRUE)
  cat("Cluster_remain:",table(obj$seurat_clusters), "\n")
  
  if (rmDoublets) {
    Idents(obj) <- "scDblFinder.class"
    obj <- subset(obj, idents = "singlet")
    cat("Cell_remain:",table(obj$scDblFinder.class), "\n")
  }
  
  return(obj)
}
```


```{r}
## ---- load data ----
AL_filtered <- Read10X(data.dir ='C:/R/SingleCell_R/AL')
Fast_filtered <- Read10X(data.dir ='C:/R/SingleCell_R/Fast')
AL_raw <- Read10X(data.dir ='C:/R/SingleCell_R/AL_Raw')
Fast_raw <- Read10X(data.dir ='C:/R/SingleCell_R/Fast_Raw')
```

```{r}
## ---- remove empty droplets ----
AL <- AL_raw %>% rmEmpty(filtered_obj = AL_filtered)
Fast <- Fast_raw %>% rmEmpty(filtered_obj = Fast_filtered)
saveRDS(AL, "AL_afterEmpty.rds")
saveRDS(Fast, "Fast_afterEmpty.rds")
```
```{r}
AL <- readRDS("AL_afterEmpty.rds")
Fast <- readRDS("Fast_afterEmpty.rds")
```


```{r fig.height=12,fig.width=12, fig.dpi=300}
## ---- main pipeline ----
ALC <- AL %>% Norm() %>% PcaUmap() %>% FindClusters(algorithm = 4, resolution = 0.5) %>%
  rmSoup(Raw_obj = AL_raw, group = "Adlib") %>% Norm() %>% PcaUmap() %>% FindClusters(algorithm = 4, resolution = 0.5) %>% FindDbl()

FastC <- Fast %>% Norm() %>% PcaUmap() %>% FindClusters(algorithm = 4, resolution = 0.5) %>%
  rmSoup(Raw_obj = Fast_raw, group = "Fast") %>% Norm() %>% PcaUmap() %>% FindClusters(algorithm = 4, resolution = 0.5) %>% FindDbl()
```


```{r height=10,fig.width=20, fig.dpi=300}
## ---- identify low-quality clusters ----
marker.1 <- FindAllMarkers(ALC, assay = "RNA", only.pos = T, min.pct = 0.25, logfc.threshold = 0.25)
marker.1 <- marker.1 %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)

marker.2 <- FindAllMarkers(FastC, assay = "RNA", only.pos = T, min.pct = 0.25,  logfc.threshold = 0.25)
marker.2 <- marker.2 %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)

(DoHeatmap(ALC, features = marker.1$gene) + NoLegend() + ggtitle('AL') + theme(plot.title = element_text(size = 15, face = "bold"))) + 
  (DoHeatmap(FastC, features = marker.2$gene) + NoLegend() + ggtitle('Fast') + theme(plot.title = element_text(size = 15, face = "bold")))
```

```{r}
## ---- remove low-quality cells ----
AL_C <- rmLowquality(ALC, LowQualityClusters = c("1", "3"), rmDoublets = T)
AL_C$group <- "AL"
Fast_C <- rmLowquality(FastC, LowQualityClusters = c("1", "2", "3"), rmDoublets = T)
Fast_C$group <- "Fast"
```


## integration 

```{r message=FALSE}
comb <- list(AL = AL_C, Fast = Fast_C)
comb <- lapply(comb, Diet)
comb <- merge(x = comb[[1]], y = comb[[2]])
comb <- NormHarmony(comb)
comb <- JoinLayers(comb)
comb <- HarmonyUmap(comb)
comb <- HarmonyTsne(comb)
comb <- FindClusters(comb, algorithm = 4, resolution = 0.5)
```

```{r fig.height=6, fig.width=6, fig.dpi=300}
DimPlot(comb, reduction = "tsne", group.by = "seurat_clusters",label = T) + NoLegend()
DimPlot(comb, reduction = "umap", group.by = "seurat_clusters",label = T) + NoLegend()
```


## Annotation

```{r}
Idents(comb) <- "seurat_clusters"
comb.markers <- FindAllMarkers(comb, assay = "RNA", only.pos = TRUE, min.pct = 0.5,
                                   logfc.threshold = 0.5)
comb.top.markers <- comb.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)
```
```{r fig.height=6,fig.width=12, fig.dpi=300}
DoHeatmap(comb, features = comb.top.markers$gene) + NoLegend() + ggtitle('Comb') +theme(plot.title = element_text(size = 10, face = "bold"))
```
```{r}
marker_sets <- list(
  Exc_shared = c("Slc17a7"),
  Inh_shared = c("Gad1", "Gad2"),

  "L2-3_IT" = c("Calb1", "Rasgrf2", "Cux2", "Nectin3"),
  "L5-6_IT" = c("Hrh3", "Cnih3", "Dkkl1", "Gfra2"),
  CT        = c("Nxph3", "Hs3st4", "Syt6", "Pcp4"),
  PT        = c("Igfbp4", "Bcl6", "Fezf2", "Bcl11b"),

  GABA_MGE  = c("Lhx6", "Pvalb", "Sst", "Tac1"),
  GABA_CGE  = c("Vip", "Reln", "Prox1", "Htr3a"),

  Ast       = c("Aldh1l1", "Aqp4", "Slc1a3", "Gfap"),
  Oligo     = c("Mbp", "Mog", "Plp1", "Mag"),
  OPC       = c("Pdgfra", "Cspg4", "Olig1", "Gpr17"),
  "Micro-PVM" = c("Tmem119", "P2ry12", "Mrc1", "C1qa"),
  Endo      = c("Pecam1", "Cldn5", "Cdh5", "Kdr"),
  VLMC      = c("Col1a1", "Col1a2", "Lum", "Dcn")
)

for (ct in names(marker_sets)) {
  genes <- intersect(marker_sets[[ct]], rownames(comb))

  for (g in genes) {
    p <- FeaturePlot(
      object      = comb,
      features    = g,
      reduction   = "umap",
      order       = TRUE
    ) + ggtitle(paste0(ct, " - ", g))
    
    print(p)
  }
}
```


```{r}
Idents(comb) <- "seurat_clusters"
new.cluster.ids <- c(
  '1' = "L5-6_IT",
  '2' = "L2-3_IT",
  '3' = "Ast",
  '4' = "L2-3_IT",
  '5' = "GABA_MGE",
  '6' = "CT",
  '7' = "VLMC",
  '8' = "PT",
  '9' = "Ast",
  '10' = "Micro-PVM",
  '11' = "Endo",
  '12' = "GABA_CGE",
  '13' = "Oligo",
  '14' = "OPC",
  '15' = "Oligo",
  '16' = "CT", 
  '17' = "Micro-PVM")
comb <- RenameIdents(comb, new.cluster.ids)
comb$bulktype <- Idents(comb)
```


```{r fig.height=8, fig.width=8, fig.dpi=300}
DimPlot(comb, reduction = "umap",group.by = "bulktype", label = T, label.size = 3, repel = T ) + NoLegend() + theme(title = element_text(size = 20))
DimPlot(comb, reduction = "tsne",group.by = "bulktype", label = T, label.size = 3, repel = T ) + NoLegend() + theme(title = element_text(size = 20))
```

```{r}
comb.markers <- FindAllMarkers(comb, assay = "RNA", only.pos = TRUE, min.pct = 0.25,
                                   logfc.threshold = 0.25)
comb.top.markers <- comb.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)
```
```{r fig.height=6,fig.width=12, fig.dpi=300}
DoHeatmap(comb, features = comb.top.markers$gene) + NoLegend() + ggtitle('Comb') +theme(plot.title = element_text(size = 10, face = "bold"))
```

```{r}
saveRDS(comb, "renamed_0703.rds")
# rm(AL_raw,Fast_raw,AL_C, Fast_C, AL, Fast, ALC, FastC)
save.image("renamed_0703.RData")
```
```{r}
comb <- readRDS("renamed_0703.rds")
```






