```{r}
rm(list = ls())
library(readxl)
library(ggplot2)
library(ggforce)
library(tidyr)
library(dplyr) 
library(tibble)
library(pheatmap)
library(RColorBrewer)
library(ggrepel)
library(plotly)
library(writexl)
```



```{r}
resS <- read_excel("Table S9. DEGs_ST_for_RRHO.xlsx")
resB <- read_excel("Table S3. Bulk_RNAsq_DEGs.xlsx")
```



```{r dpi = 300, fig.width=7, fig.height=7}
## ---- Fig5A ----
library(RRHO2)

gene_S <- "gene";  p_S <- "pvalue";  lfc_S <- "log2FoldChange"
gene_B <- "gene";  p_B <- "pvalue";  lfc_B <- "log2FoldChange"

keep  <- intersect(resS[[gene_S]], resB[[gene_B]])
iS <- match(keep, resS[[gene_S]]); iB <- match(keep, resB[[gene_B]])

s1 <- -log10(resS[[p_S]][iS]) * sign(resS[[lfc_S]][iS])
s2 <- -log10(resB[[p_B]][iB]) * sign(resB[[lfc_B]][iB])

gene_list1 <- data.frame(Genes = keep, DDE = s1)
gene_list2 <- data.frame(Genes = keep, DDE = s2)

obj <- RRHO2_initialize(gene_list1, gene_list2,
                        labels = c("ST", "Bulk RNA"),
                        log10.ind = TRUE, multipleTesting = "BH", boundary = 0.025)

RRHO2_heatmap(obj)
```
```{r dpi = 300, fig.width=7, fig.height=7}
## ---- Fig5B ----
RRHO2_vennDiagram(obj, type = "uu")
RRHO2_vennDiagram(obj, type = "dd")
```





